import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "Rick Rolling / Hong Lola vending machine",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-[#314369]">
      <head>
        <link
          href="https://cdn.jsdelivr.net/gh/sun-typeface/SUITE@2/fonts/static/woff2/SUITE.css"
          rel="stylesheet"
        />
      </head>
      <body className="font-SUITE text-white">
        <main className="flex flex-col justify-center items-center break-keep m-40">
          {children}
        </main>
      </body>
    </html>
  );
}
